docker:
  db: {}
domains: []
git:
  main_deployment_remote_name: github
  publication_strategy: main_push
global:
  authors:
    email: contact@syrtis.ai
    name: weeger
  name: python_client
  type: app
  vendor: syrtis
  version: 8.0.0
wex:
  migration: 1
  version: 6.0.112
